// This file is auto-generated by @hey-api/openapi-ts

export const Body_inpainting_remove_objectSchema = {
    properties: {
        image: {
            type: 'string',
            format: 'binary',
            title: 'Image'
        },
        mask: {
            type: 'string',
            format: 'binary',
            title: 'Mask'
        },
        prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prompt'
        },
        negative_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Negative Prompt'
        },
        steps: {
            type: 'integer',
            title: 'Steps',
            default: 40
        },
        guidance_scale: {
            type: 'number',
            title: 'Guidance Scale',
            default: 4.5
        },
        strength: {
            type: 'number',
            title: 'Strength',
            default: 0.95
        },
        seed: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seed'
        },
        mask_dilation: {
            type: 'integer',
            title: 'Mask Dilation',
            default: 15
        },
        mask_feather: {
            type: 'number',
            title: 'Mask Feather',
            default: 5
        }
    },
    type: 'object',
    required: ['image', 'mask'],
    title: 'Body_inpainting-remove_object'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_segmentation_predict_segmentationSchema = {
    properties: {
        image: {
            type: 'string',
            format: 'binary',
            title: 'Image'
        },
        points: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Points'
        },
        point_labels: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Point Labels'
        },
        box: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Box'
        },
        text_prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Text Prompt'
        },
        circle_box: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Circle Box'
        },
        mask_threshold: {
            type: 'number',
            title: 'Mask Threshold',
            default: 0.35
        },
        feather_radius: {
            type: 'number',
            title: 'Feather Radius',
            default: 0
        }
    },
    type: 'object',
    required: ['image'],
    title: 'Body_segmentation-predict_segmentation'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InpaintingResponseSchema = {
    properties: {
        result_png_base64: {
            type: 'string',
            title: 'Result Png Base64'
        },
        debug_crop_png_base64: {
            type: 'string',
            title: 'Debug Crop Png Base64'
        },
        width: {
            type: 'integer',
            title: 'Width'
        },
        height: {
            type: 'integer',
            title: 'Height'
        },
        duration_ms: {
            type: 'integer',
            title: 'Duration Ms'
        },
        seed_used: {
            type: 'integer',
            title: 'Seed Used'
        }
    },
    type: 'object',
    required: ['result_png_base64', 'debug_crop_png_base64', 'width', 'height', 'duration_ms', 'seed_used'],
    title: 'InpaintingResponse'
} as const;

export const InpaintingStatusResponseSchema = {
    properties: {
        model: {
            type: 'string',
            title: 'Model'
        },
        device: {
            type: 'string',
            title: 'Device'
        },
        cuda_available: {
            type: 'boolean',
            title: 'Cuda Available'
        },
        loaded: {
            type: 'boolean',
            title: 'Loaded'
        }
    },
    type: 'object',
    required: ['model', 'device', 'cuda_available', 'loaded'],
    title: 'InpaintingStatusResponse'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const SegmentationPredictResponseSchema = {
    properties: {
        width: {
            type: 'integer',
            title: 'Width'
        },
        height: {
            type: 'integer',
            title: 'Height'
        },
        processed_width: {
            type: 'integer',
            title: 'Processed Width'
        },
        processed_height: {
            type: 'integer',
            title: 'Processed Height'
        },
        best_score: {
            type: 'number',
            title: 'Best Score'
        },
        mask_png_base64: {
            type: 'string',
            title: 'Mask Png Base64'
        },
        overlay_png_base64: {
            type: 'string',
            title: 'Overlay Png Base64'
        }
    },
    type: 'object',
    required: ['width', 'height', 'processed_width', 'processed_height', 'best_score', 'mask_png_base64', 'overlay_png_base64'],
    title: 'SegmentationPredictResponse'
} as const;

export const SegmentationStatusSchema = {
    properties: {
        model: {
            type: 'string',
            title: 'Model'
        },
        device: {
            type: 'string',
            title: 'Device'
        },
        cuda_available: {
            type: 'boolean',
            title: 'Cuda Available'
        },
        cuda_device_count: {
            type: 'integer',
            title: 'Cuda Device Count'
        },
        checkpoint_path: {
            type: 'string',
            title: 'Checkpoint Path'
        },
        checkpoint_exists: {
            type: 'boolean',
            title: 'Checkpoint Exists'
        },
        loaded: {
            type: 'boolean',
            title: 'Loaded'
        }
    },
    type: 'object',
    required: ['model', 'device', 'cuda_available', 'cuda_device_count', 'checkpoint_path', 'checkpoint_exists', 'loaded'],
    title: 'SegmentationStatus'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;