// This file is auto-generated by @hey-api/openapi-ts

export type Body_inpainting_remove_object = {
    image: (Blob | File);
    mask: (Blob | File);
    prompt?: (string | null);
    negative_prompt?: (string | null);
    steps?: number;
    guidance_scale?: number;
    strength?: number;
    seed?: (number | null);
    mask_dilation?: number;
    mask_feather?: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_segmentation_predict_segmentation = {
    image: (Blob | File);
    points?: (string | null);
    point_labels?: (string | null);
    box?: (string | null);
    text_prompt?: (string | null);
    circle_box?: (string | null);
    mask_threshold?: number;
    feather_radius?: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InpaintingResponse = {
    result_png_base64: string;
    debug_crop_png_base64: string;
    width: number;
    height: number;
    duration_ms: number;
    seed_used: number;
};

export type InpaintingStatusResponse = {
    model: string;
    device: string;
    cuda_available: boolean;
    loaded: boolean;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type SegmentationPredictResponse = {
    width: number;
    height: number;
    processed_width: number;
    processed_height: number;
    best_score: number;
    mask_png_base64: string;
    overlay_png_base64: string;
};

export type SegmentationStatus = {
    model: string;
    device: string;
    cuda_available: boolean;
    cuda_device_count: number;
    checkpoint_path: string;
    checkpoint_exists: boolean;
    loaded: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type InpaintingInpaintingStatusResponse = (InpaintingStatusResponse);

export type InpaintingRemoveObjectData = {
    formData: Body_inpainting_remove_object;
};

export type InpaintingRemoveObjectResponse = (InpaintingResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type SegmentationSegmentationStatusResponse = (SegmentationStatus);

export type SegmentationPredictSegmentationData = {
    formData: Body_segmentation_predict_segmentation;
};

export type SegmentationPredictSegmentationResponse = (SegmentationPredictResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);